### PR TITLE
Implementing the true Wolter optics process

### PR DESCRIPTION
**Pull request by jovoy**
jovoy Large: 583 [](https://gitlab.cern.ch/rest-for-physics/axionlib/-/commits/true_wolter_optics) [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/true_wolter_optics)

A new class TRestAxionTrueWolterOptics that only differs slightly to TRestAxionWolterOptics will be implemented that allows the usage of the reflection on a parabolic and a hyperbolic mirror instead of two cone shaped ones.

Gives the following result with a well aligned optic:
optics_Yaw_0 0_Dev_0 0trueWolter

In comparison to the cone shaped procedure:

optics_Yaw_0 0_Dev_0 0

### CODE REVIEW

**Comment by jovoy** [comment]
Need to add vertex and mirror axis to this and to TRestPhysics in the framework.

**Comment by jovoy** [comment]
Result when the optic is tilted by a yaw angle of 0.01°:
optics_Yaw_0 01_Dev_0 0

It's odd that the efficiency is so low at no tilt.

**Comment by jovoy** [comment]
Problem solved in framework in TRestPhysics

optics_Yaw_0 0_Dev_0 0

**Review by jgalan — APPROVED** [review]
So, finally there was a fix at `TRestPhysics` for solving the parallel flux issue?

It is ok with me to merge these changes to master, I think it would be interesting to create a pipeline that launches the simulations with low statistics (running in few seconds), then gets the spot size, simply using the sigma of true wolter and conic wolter, then cross-check that the values keep the same in future versions of the code.

Such as it is done inside `.gitlab-ci.yml` for the magnetic field:

```
magneticField:
  type: metadata
  script:
    - . ${CI_PROJECT_DIR}/framework/source/libraries/axion/external/solarAxionFlux/bin/thisSolarAxionFluxLib.sh
    - . ${CI_PROJECT_DIR}/install/thisREST.sh
    - cd ${CI_PROJECT_DIR}/pipeline/magneticField/
    - ./magneticField.py
    - cd trilinear
    - restRoot -b -q GetMagneticField_test.C
    - cd ${CI_PROJECT_DIR}/pipeline/magneticField/boundary/
    - restRoot -b -q Boundaries_test.C
  except:
      variables:
        - $CRONJOB
```

**Pull request merged**
