### PR TITLE
Fixing validation pipelines

### PR DESCRIPTION
**Pull request by jgalan**
jgalan Ok: 17 [](https://gitlab.cern.ch/rest-for-physics/axionlib/-/commits/jovoy_acceptance) [](https://github.com/rest-for-physics/axionlib/commits/jovoy_acceptance)

Adding required data downloaded as wget to the pipeline

### CODE REVIEW

**Review by lobis — APPROVED** [review]

**Comment by jgalan** [comment]
I do not understand what it is going on here. It seems that the validation pipeline for axionlib is the master one and not the present branch? @juanangp @lobis

**Comment by jgalan** [comment]
Also I don't understand why the GitHub badge shows "No status", it seems it happens the same in other libraries, but not in main framework repository.

**Comment by juanangp** [comment]
> I modified the `workflow/validation.yml` for the job that is failing, but changes do not appear on the pipeline.

Indeed, the validation workflows are pointing to `master`. I think you should create a new branch in framework and modify the following lines:
https://github.com/rest-for-physics/framework/blob/babeff3be96b7e433ebcf42e4c55b4ae82530275/.github/workflows/validation.yml#L656
```
    uses: rest-for-physics/axionlib/.github/workflows/validation.yml@jovoy_acceptance
```
Then on axion lib workflow:
https://github.com/rest-for-physics/axionlib/blob/9536fb7f118467e15cfe9ed85ee3556e0647db61/.github/workflows/frameworkValidation.yml#L23
```
   uses: rest-for-physics/framework/.github/workflows/validation.yml@jovoy_acceptance
```

Then after merge you should revert these changes.

In order to avoid it we can try to move to a versioning for the workflows, but I am not sure how can this be handled, another option is to create a submodule with the workflows. But we the new scheme is difficult to handle the pipelines of the different submodules.

You can create an issue about this if you think that should be done in a different way.

**Comment by jgalan** [comment]
I understand that in the framework we use master for validation. Although, an interesting choice would be to use an existing branch with the same name as the present framework branch, and if it does not exist, then use the `master` branch.

However, It could not be fixed inside `axionlib` by skipping the framework/axionlib@master validation and adding the validation of the axionlib@branch itself?

I don't see the direct validation of this branch in the list.

**Comment by jgalan** [comment]
Perhaps we need a script that identifies if the present branch exists in the submodule and returns `master` if not.

```
echo "branchAtModuleExists.sh ${{ env.BRANCH_NAME }}"
```

This script would return the name of the branch in the sub-module if it exists, or `master` if it does not exists.

So, we would add

```
echo "branchAtModuleExists.sh ${{ env.BRANCH_NAME }}" >> $VALIDATION_BRANCH
uses: rest-for-physics/framework/.github/workflows/validation.yml@$VALIDATION_BRANCH
```

**Comment by juanangp** [comment]
> I understand that in the framework we use master for validation. Although, an interesting choice would be to use an existing branch with the same name as the present framework branch, and if it does not exist, then use the `master` branch.
> 
> However, It could not be fixed inside `axionlib` by skipping the framework/axionlib@master validation and adding the validation of the axionlib@branch itself?
> 
> I don't see the direct validation of this branch in the list.

Since we trigger all the submodule validation pipelines, the validation is pointing to master, if you want that the validation points to your current branch it is not straightforward, but can be done, please create an issue about it. For the time being you can accept the solution that I proposed.

**Comment by lobis** [comment]
Should this PR be merge @jgalan ?

**Pull request merged**
