### PR TITLE
External rotation for acceptance study

### PR DESCRIPTION
**Pull request by jovoy**
jovoy Medium: 225 [](https://gitlab.cern.ch/rest-for-physics/axionlib/-/commits/jovoy_acceptance) [](https://github.com/rest-for-physics/axionlib/commits/jovoy_acceptance)

### CODE REVIEW

**Comment by jgalan** [comment]
Because you named it `Setup` I am guessing you want to introduce a general angle that rotates all the components?

The general alignment angle of the setup could be mocked by rotating the source, i.e. the sun. Isn't?

Or, you want to rotate from which external center?

**Comment by jgalan** [comment]
Actually, the `TRestAxionGeneratorProcess` inherits from `TRestEventProcess`, it should be updated to use `TRestAxionEventProcess` and use the values of `yaw`, `pitch` and `center` to rotate the original axion flux so that it mocks the rotation of the full setup.

**Comment by jovoy** [comment]
> Because you named it `Setup` I am guessing you want to introduce a general angle that rotates all the components?
> 
> The general alignment angle of the setup could be mocked by rotating the source, i.e. the sun. Isn't?
> 
> Or, you want to rotate from which external center?

No, it's for the acceptance study so I want to rotate any object (detector, optics, magnet bore) around the center spot of the BabyIAXO setup as we had discussed. I called it external rotation because it's outside of the object.

**Comment by jovoy** [comment]
> Actually, the `TRestAxionGeneratorProcess` inherits from `TRestEventProcess`, it should be updated to use `TRestAxionEventProcess` and implement the use of the values of `yaw`, `pitch` and `center` to rotate the original axion flux inside the `TRestAxionGeneratorProcess` implementation so that it mocks the rotation of the full setup.

I thought so too first, but I need to do the translate operation with the center as the center of the object and then this new rotation operation with the center as described in the last comment. I need to do these operations at the same time so they have to be different centers. I f I would now use yaw and pitch it would also turn around the center of the object and that's not what we want for the acceptance study, so I made new variables.

But we can change the names; CenterAccept because of the acceptance study was my other idea.

**Comment by jgalan** [comment]
Perhaps we could quickly rediscuss this online.

_Rotating the sun_ from any center you chose would not be equivalent to the additional rotation you are introducing?

You could chose to rotate the sun around the spot, or around the center of the optics, this would be a user choice.

But do you really need to introduce an extra yaw/pitch rotation from a different center at each process?

**Review by jgalan — APPROVED** [review]

**Pull request merged**
